// Copyright 2026 Surabhi Pradhan.
// SPDX-License-Identifier: MIT

// Code generated by controller-gen. DO NOT EDIT.
// Regenerate with: make generate
//
// NOTE: This file was initially hand-authored to allow the project to compile
// before controller-gen is available. Running `make generate` will overwrite
// it with the tool-generated version.

//go:build !ignore_autogenerated

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of AgentInstrumentation into another
// AgentInstrumentation instance. Called by DeepCopy and DeepCopyObject.
func (in *AgentInstrumentation) DeepCopyInto(out *AgentInstrumentation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of AgentInstrumentation.
func (in *AgentInstrumentation) DeepCopy() *AgentInstrumentation {
	if in == nil {
		return nil
	}
	out := new(AgentInstrumentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AgentInstrumentation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of AgentInstrumentationList into another
// AgentInstrumentationList instance.
func (in *AgentInstrumentationList) DeepCopyInto(out *AgentInstrumentationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentInstrumentation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of AgentInstrumentationList.
func (in *AgentInstrumentationList) DeepCopy() *AgentInstrumentationList {
	if in == nil {
		return nil
	}
	out := new(AgentInstrumentationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AgentInstrumentationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of AgentInstrumentationSpec into another
// AgentInstrumentationSpec instance.
func (in *AgentInstrumentationSpec) DeepCopyInto(out *AgentInstrumentationSpec) {
	*out = *in
	// Enabled, AEPServerURL, SidecarImage are value types — copied by *out = *in above.

	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	// ResourceRequirements contains maps (Limits, Requests) — use its DeepCopyInto.
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			// EnvVar may contain a *EnvVarSource pointer — use its DeepCopyInto.
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of AgentInstrumentationSpec.
func (in *AgentInstrumentationSpec) DeepCopy() *AgentInstrumentationSpec {
	if in == nil {
		return nil
	}
	out := new(AgentInstrumentationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of AgentInstrumentationStatus into another
// AgentInstrumentationStatus instance.
func (in *AgentInstrumentationStatus) DeepCopyInto(out *AgentInstrumentationStatus) {
	*out = *in
	// ObservedGeneration and InjectedCount are value types — copied by *out = *in above.

	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			// metav1.Condition contains a metav1.Time (embeds time.Time with *Location)
			// — use its DeepCopyInto.
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of AgentInstrumentationStatus.
func (in *AgentInstrumentationStatus) DeepCopy() *AgentInstrumentationStatus {
	if in == nil {
		return nil
	}
	out := new(AgentInstrumentationStatus)
	in.DeepCopyInto(out)
	return out
}
