"""Unit tests for aep.verify_audit_bundle (offline audit-bundle verification).

Cross-language parity is locked by the shared known-answer bundle fixture
(``tests/fixtures/audit/kat-bundle.json``), generated by the server's
``buildAuditBundle`` and verified identically by the server and the Go/Node SDKs.
"""

import copy
import json
from pathlib import Path

import pytest

from aep import verify_audit_bundle

# Shared KAT generated from the server (src/audit.js buildAuditBundle).
_KAT_SECRET = "shared-secret-123"
_KAT_CONTENT_DIGEST = "3de94f67e3ff35fc9b3e31c2e5efc1932f9e950cc6be0813eed571271ad6f6d5"
_KAT_SIGNATURE = "D6IW2aVORoxIZWy+LiWUrZ08QKLkzFo9uTEySZlcWVA="

_FIXTURE = (
    Path(__file__).resolve().parents[4] / "tests" / "fixtures" / "audit" / "kat-bundle.json"
)


def _load_bundle():
    with _FIXTURE.open(encoding="utf-8") as fh:
        return json.load(fh)


def test_known_answer_bundle_verifies():
    bundle = _load_bundle()
    # The fixture itself carries the server-computed digest + signature.
    assert bundle["manifest"]["content_digest"] == _KAT_CONTENT_DIGEST
    assert bundle["signature"]["value"] == _KAT_SIGNATURE

    result = verify_audit_bundle(bundle, _KAT_SECRET)
    assert result["valid"] is True
    assert result["content_digest_match"] is True
    assert result["manifest_signature_valid"] is True
    assert result["errors"] == []
    assert len(result["per_event"]) == 2


def test_wrong_secret_fails_signature():
    result = verify_audit_bundle(_load_bundle(), "not-the-secret")
    assert result["valid"] is False
    assert result["manifest_signature_valid"] is False
    # The content digest does not depend on the secret, so it still matches.
    assert result["content_digest_match"] is True


def test_payload_tampering_breaks_content_digest():
    bundle = _load_bundle()
    bundle["events"][0]["payload"]["n"] = 999  # mutate a nested payload field
    result = verify_audit_bundle(bundle, _KAT_SECRET)
    assert result["valid"] is False
    assert result["content_digest_match"] is False
    assert any("content_digest" in e for e in result["errors"])


def test_event_reordering_breaks_content_digest():
    bundle = _load_bundle()
    bundle["events"].reverse()
    result = verify_audit_bundle(bundle, _KAT_SECRET)
    assert result["valid"] is False
    assert result["content_digest_match"] is False


def test_manifest_tampering_breaks_signature():
    bundle = _load_bundle()
    bundle["manifest"]["tenant_id"] = "attacker"
    result = verify_audit_bundle(bundle, _KAT_SECRET)
    assert result["valid"] is False
    assert result["manifest_signature_valid"] is False


def test_dropping_an_event_is_detected():
    bundle = _load_bundle()
    bundle["events"].pop()
    result = verify_audit_bundle(bundle, _KAT_SECRET)
    assert result["valid"] is False
    # both the digest and the event_count cross-check fire
    assert result["content_digest_match"] is False
    assert any("event_count" in e for e in result["errors"])


def test_version_downgrade_is_flagged():
    bundle = _load_bundle()
    bundle["aep_audit_version"] = "9.9.9"  # unsigned top-level copy edited
    result = verify_audit_bundle(bundle, _KAT_SECRET)
    assert result["valid"] is False
    assert any("aep_audit_version mismatch" in e for e in result["errors"])


def test_unsupported_signature_alg_is_rejected():
    bundle = _load_bundle()
    bundle["signature"]["alg"] = "rsa-sha256"
    result = verify_audit_bundle(bundle, _KAT_SECRET)
    assert result["valid"] is False
    assert any("Unsupported signature algorithm" in e for e in result["errors"])


@pytest.mark.parametrize("bad", [None, 42, "string", []])
def test_non_dict_bundle_fails_gracefully(bad):
    result = verify_audit_bundle(bad, _KAT_SECRET)
    assert result["valid"] is False
    assert result["errors"]


def test_empty_secret_fails_gracefully():
    result = verify_audit_bundle(_load_bundle(), "")
    assert result["valid"] is False
    assert any("secret" in e for e in result["errors"])
